import type { SynthPreset } from "../types/presets";

export const DEFAULT_PRESETS: SynthPreset[] = [
  // Analog Mono Presets
  {
    id: "analog_mono_bass",
    name: "Analog Bass",
    synthType: "analog",
    polyphony: "mono",
    parameters: {
      volume: 0.5,
      ampAttack: 0.01,
      ampDecay: 0.3,
      ampSustain: 0.7,
      ampRelease: 0.2,
      oscillatorType: "sawtooth",
      filterFrequency: 800,
      filterResonance: 8,
      filterAttack: 0.01,
      filterDecay: 0.2,
      filterSustain: 0.3,
      filterRelease: 0.1,
      modulationIndex: 10,
      harmonicity: 1,
      modAttack: 0.01,
      modDecay: 0.1,
      modSustain: 0.5,
      modRelease: 0.3,
    },
    createdAt: new Date("2024-01-01T00:00:00Z"),
    updatedAt: new Date("2024-01-01T00:00:00Z"),
  },
  {
    id: "analog_mono_lead",
    name: "Analog Lead",
    synthType: "analog",
    polyphony: "mono",
    parameters: {
      volume: 0.5,
      ampAttack: 0.02,
      ampDecay: 0.1,
      ampSustain: 0.8,
      ampRelease: 0.5,
      oscillatorType: "square",
      filterFrequency: 2000,
      filterResonance: 12,
      filterAttack: 0.02,
      filterDecay: 0.3,
      filterSustain: 0.6,
      filterRelease: 0.4,
      modulationIndex: 10,
      harmonicity: 1,
      modAttack: 0.01,
      modDecay: 0.1,
      modSustain: 0.5,
      modRelease: 0.3,
    },
    createdAt: new Date("2024-01-01T00:00:00Z"),
    updatedAt: new Date("2024-01-01T00:00:00Z"),
  },

  // Analog Poly Presets
  {
    id: "analog_poly_pad",
    name: "Analog Pad",
    synthType: "analog",
    polyphony: "poly",
    parameters: {
      volume: 0.5,
      ampAttack: 0.8,
      ampDecay: 0.5,
      ampSustain: 0.7,
      ampRelease: 1.5,
      oscillatorType: "sawtooth",
      filterFrequency: 1200,
      filterResonance: 4,
      filterAttack: 0.6,
      filterDecay: 0.4,
      filterSustain: 0.8,
      filterRelease: 1.2,
      modulationIndex: 10,
      harmonicity: 1,
      modAttack: 0.01,
      modDecay: 0.1,
      modSustain: 0.5,
      modRelease: 0.3,
    },
    createdAt: new Date("2024-01-01T00:00:00Z"),
    updatedAt: new Date("2024-01-01T00:00:00Z"),
  },
  {
    id: "analog_poly_pluck",
    name: "Analog Pluck",
    synthType: "analog",
    polyphony: "poly",
    parameters: {
      volume: 0.5,
      ampAttack: 0.01,
      ampDecay: 0.4,
      ampSustain: 0.0,
      ampRelease: 0.3,
      oscillatorType: "triangle",
      filterFrequency: 3000,
      filterResonance: 6,
      filterAttack: 0.01,
      filterDecay: 0.3,
      filterSustain: 0.0,
      filterRelease: 0.2,
      modulationIndex: 10,
      harmonicity: 1,
      modAttack: 0.01,
      modDecay: 0.1,
      modSustain: 0.5,
      modRelease: 0.3,
    },
    createdAt: new Date("2024-01-01T00:00:00Z"),
    updatedAt: new Date("2024-01-01T00:00:00Z"),
  },

  // FM Mono Presets
  {
    id: "fm_mono_bass",
    name: "FM Bass",
    synthType: "fm",
    polyphony: "mono",
    parameters: {
      volume: 0.5,
      ampAttack: 0.01,
      ampDecay: 0.2,
      ampSustain: 0.8,
      ampRelease: 0.3,
      oscillatorType: "sawtooth",
      filterFrequency: 1000,
      filterResonance: 5,
      filterAttack: 0.01,
      filterDecay: 0.1,
      filterSustain: 0.5,
      filterRelease: 0.3,
      modulationIndex: 15,
      harmonicity: 0.5,
      modAttack: 0.01,
      modDecay: 0.1,
      modSustain: 0.6,
      modRelease: 0.2,
    },
    createdAt: new Date("2024-01-01T00:00:00Z"),
    updatedAt: new Date("2024-01-01T00:00:00Z"),
  },
  {
    id: "fm_mono_lead",
    name: "FM Lead",
    synthType: "fm",
    polyphony: "mono",
    parameters: {
      volume: 0.5,
      ampAttack: 0.02,
      ampDecay: 0.1,
      ampSustain: 0.9,
      ampRelease: 0.4,
      oscillatorType: "sawtooth",
      filterFrequency: 1000,
      filterResonance: 5,
      filterAttack: 0.01,
      filterDecay: 0.1,
      filterSustain: 0.5,
      filterRelease: 0.3,
      modulationIndex: 25,
      harmonicity: 2,
      modAttack: 0.02,
      modDecay: 0.3,
      modSustain: 0.4,
      modRelease: 0.3,
    },
    createdAt: new Date("2024-01-01T00:00:00Z"),
    updatedAt: new Date("2024-01-01T00:00:00Z"),
  },

  // FM Poly Presets
  {
    id: "fm_poly_electric_piano",
    name: "FM Electric Piano",
    synthType: "fm",
    polyphony: "poly",
    parameters: {
      volume: 0.5,
      ampAttack: 0.01,
      ampDecay: 0.3,
      ampSustain: 0.3,
      ampRelease: 0.8,
      oscillatorType: "sawtooth",
      filterFrequency: 1000,
      filterResonance: 5,
      filterAttack: 0.01,
      filterDecay: 0.1,
      filterSustain: 0.5,
      filterRelease: 0.3,
      modulationIndex: 12,
      harmonicity: 1,
      modAttack: 0.01,
      modDecay: 0.2,
      modSustain: 0.0,
      modRelease: 0.5,
    },
    createdAt: new Date("2024-01-01T00:00:00Z"),
    updatedAt: new Date("2024-01-01T00:00:00Z"),
  },
  {
    id: "fm_poly_bell",
    name: "FM Bell",
    synthType: "fm",
    polyphony: "poly",
    parameters: {
      volume: 0.5,
      ampAttack: 0.01,
      ampDecay: 1.0,
      ampSustain: 0.2,
      ampRelease: 2.0,
      oscillatorType: "sawtooth",
      filterFrequency: 1000,
      filterResonance: 5,
      filterAttack: 0.01,
      filterDecay: 0.1,
      filterSustain: 0.5,
      filterRelease: 0.3,
      modulationIndex: 20,
      harmonicity: 3.5,
      modAttack: 0.01,
      modDecay: 0.8,
      modSustain: 0.0,
      modRelease: 1.5,
    },
    createdAt: new Date("2024-01-01T00:00:00Z"),
    updatedAt: new Date("2024-01-01T00:00:00Z"),
  },
]; 