import type { EffectConfig, EffectType } from '../types';

export const EFFECT_CONFIGS: Record<EffectType, EffectConfig> = {
  reverb: {
    type: 'reverb',
    name: 'Reverb',
    icon: '🌊',
    parameters: [
      {
        name: 'Room Size',
        value: 0.5,
        min: 0,
        max: 1,
        step: 0.01,
        type: 'knob',
      },
      {
        name: 'Decay Time',
        value: 0.4,
        min: 0.1,
        max: 10,
        step: 0.1,
        type: 'knob',
        unit: 's',
      },
      {
        name: 'Pre-Delay',
        value: 0.03,
        min: 0,
        max: 0.1,
        step: 0.001,
        type: 'knob',
        unit: 's',
      },
      {
        name: 'Dry/Wet',
        value: 0.5,
        min: 0,
        max: 1,
        step: 0.01,
        type: 'knob',
      },
    ],
  },
  delay: {
    type: 'delay',
    name: 'Delay',
    icon: '📡',
    parameters: [
      {
        name: 'Time',
        value: 0.25,
        min: 0.01,
        max: 1.0,
        step: 0.01,
        type: 'knob',
        unit: 's',
      },
      {
        name: 'Feedback',
        value: 0.3,
        min: 0,
        max: 0.95,
        step: 0.01,
        type: 'knob',
      },
      {
        name: 'Dry/Wet',
        value: 0.5,
        min: 0,
        max: 1,
        step: 0.01,
        type: 'knob',
      },
    ],
  },
  filter: {
    type: 'filter',
    name: 'Filter',
    icon: '🎛️',
    parameters: [
      {
        name: 'Frequency',
        value: 1000,
        min: 20,
        max: 20000,
        step: 1,
        type: 'knob',
        unit: 'Hz',
        curve: 'logarithmic',
      },
      {
        name: 'Resonance',
        value: 1,
        min: 0.1,
        max: 30,
        step: 0.1,
        type: 'knob',
      },
      {
        name: 'Type',
        value: 0,
        min: 0,
        max: 2,
        step: 1,
        type: 'slider',
      },
      {
        name: 'Dry/Wet',
        value: 0.5,
        min: 0,
        max: 1,
        step: 0.01,
        type: 'knob',
      },
    ],
  },
  compressor: {
    type: 'compressor',
    name: 'Compressor',
    icon: '🗜️',
    parameters: [
      {
        name: 'Threshold',
        value: -24,
        min: -100,
        max: 0,
        step: 0.1,
        type: 'knob',
        unit: 'dB',
      },
      {
        name: 'Ratio',
        value: 4,
        min: 1,
        max: 20,
        step: 0.1,
        type: 'knob',
      },
      {
        name: 'Attack',
        value: 0.003,
        min: 0.0001,
        max: 1,
        step: 0.0001,
        type: 'knob',
        unit: 's',
      },
      {
        name: 'Release',
        value: 0.25,
        min: 0.01,
        max: 2,
        step: 0.01,
        type: 'knob',
        unit: 's',
      },
      {
        name: 'Dry/Wet',
        value: 0.5,
        min: 0,
        max: 1,
        step: 0.01,
        type: 'knob',
      },
    ],
  },
  autofilter: {
    type: 'autofilter',
    name: 'AutoFilter',
    icon: '🔄',
    parameters: [
      {
        name: 'Frequency',
        value: 8.0,
        min: 1,
        max: 20,
        step: 0.1,
        type: 'knob',
        unit: 'Hz',
      },
      {
        name: 'Base Frequency',
        value: 400,
        min: 50,
        max: 2000,
        step: 10,
        type: 'knob',
        unit: 'Hz',
        curve: 'logarithmic',
      },
      {
        name: 'Octaves',
        value: 2.6,
        min: 0.5,
        max: 8,
        step: 0.1,
        type: 'knob',
      },
      {
        name: 'Filter Type',
        value: 0,
        min: 0,
        max: 2,
        step: 1,
        type: 'slider',
      },
      {
        name: 'Dry/Wet',
        value: 0.5,
        min: 0,
        max: 1,
        step: 0.01,
        type: 'knob',
      },
    ],
  },
  autopanner: {
    type: 'autopanner',
    name: 'AutoPanner',
    icon: '◀️▶️',
    parameters: [
      {
        name: 'Frequency',
        value: 1,
        min: 0.1,
        max: 20,
        step: 0.1,
        type: 'knob',
        unit: 'Hz',
      },
      {
        name: 'Depth',
        value: 1,
        min: 0,
        max: 1,
        step: 0.01,
        type: 'knob',
      },
      {
        name: 'Dry/Wet',
        value: 0.5,
        min: 0,
        max: 1,
        step: 0.01,
        type: 'knob',
      },
    ],
  },
  autowah: {
    type: 'autowah',
    name: 'AutoWah',
    icon: '🌊',
    parameters: [
      {
        name: 'Base Frequency',
        value: 100,
        min: 50,
        max: 1000,
        step: 10,
        type: 'knob',
        unit: 'Hz',
        curve: 'logarithmic',
      },
      {
        name: 'Octaves',
        value: 6,
        min: 1,
        max: 8,
        step: 0.1,
        type: 'knob',
      },
      {
        name: 'Sensitivity',
        value: 0,
        min: -40,
        max: 0,
        step: 1,
        type: 'knob',
        unit: 'dB',
      },
      {
        name: 'Q',
        value: 2,
        min: 0.1,
        max: 30,
        step: 0.1,
        type: 'knob',
      },
      {
        name: 'Dry/Wet',
        value: 0.5,
        min: 0,
        max: 1,
        step: 0.01,
        type: 'knob',
      },
    ],
  },
  bitcrusher: {
    type: 'bitcrusher',
    name: 'BitCrusher',
    icon: '🔥',
    parameters: [
      {
        name: 'Bits',
        value: 8,
        min: 1,
        max: 16,
        step: 1,
        type: 'knob',
      },
      {
        name: 'Dry/Wet',
        value: 0.5,
        min: 0,
        max: 1,
        step: 0.01,
        type: 'knob',
      },
    ],
  },
  chorus: {
    type: 'chorus',
    name: 'Chorus',
    icon: '🌈',
    parameters: [
      {
        name: 'Frequency',
        value: 1.5,
        min: 0.01,
        max: 20,
        step: 0.01,
        type: 'knob',
        unit: 'Hz',
      },
      {
        name: 'Delay Time',
        value: 0.0035,
        min: 0.001,
        max: 0.02,
        step: 0.0001,
        type: 'knob',
        unit: 's',
      },
      {
        name: 'Depth',
        value: 0.7,
        min: 0,
        max: 1,
        step: 0.01,
        type: 'knob',
      },
      {
        name: 'Spread',
        value: 180,
        min: 0,
        max: 180,
        step: 1,
        type: 'knob',
        unit: '°',
      },
      {
        name: 'Dry/Wet',
        value: 0.5,
        min: 0,
        max: 1,
        step: 0.01,
        type: 'knob',
      },
    ],
  },
  distortion: {
    type: 'distortion',
    name: 'Distortion',
    icon: '⚡',
    parameters: [
      {
        name: 'Distortion',
        value: 0.4,
        min: 0,
        max: 1,
        step: 0.01,
        type: 'knob',
      },
      {
        name: 'Oversample',
        value: 0,
        min: 0,
        max: 2,
        step: 1,
        type: 'slider',
      },
      {
        name: 'Dry/Wet',
        value: 0.5,
        min: 0,
        max: 1,
        step: 0.01,
        type: 'knob',
      },
    ],
  },
  phaser: {
    type: 'phaser',
    name: 'Phaser',
    icon: '🌀',
    parameters: [
      {
        name: 'Frequency',
        value: 0.5,
        min: 0.01,
        max: 10,
        step: 0.01,
        type: 'knob',
        unit: 'Hz',
      },
      {
        name: 'Octaves',
        value: 3,
        min: 0.5,
        max: 8,
        step: 0.1,
        type: 'knob',
      },
      {
        name: 'Base Frequency',
        value: 350,
        min: 50,
        max: 2000,
        step: 10,
        type: 'knob',
        unit: 'Hz',
        curve: 'logarithmic',
      },
      {
        name: 'Stages',
        value: 4,
        min: 2,
        max: 8,
        step: 1,
        type: 'knob',
      },
      {
        name: 'Q',
        value: 10,
        min: 0.1,
        max: 30,
        step: 0.1,
        type: 'knob',
      },
      {
        name: 'Dry/Wet',
        value: 0.5,
        min: 0,
        max: 1,
        step: 0.01,
        type: 'knob',
      },
    ],
  },
  pingpongdelay: {
    type: 'pingpongdelay',
    name: 'Ping Pong Delay',
    icon: '🏓',
    parameters: [
      {
        name: 'Delay Time',
        value: 0.25,
        min: 0.01,
        max: 1,
        step: 0.01,
        type: 'knob',
        unit: 's',
      },
      {
        name: 'Feedback',
        value: 0.3,
        min: 0,
        max: 0.95,
        step: 0.01,
        type: 'knob',
      },
      {
        name: 'Dry/Wet',
        value: 0.5,
        min: 0,
        max: 1,
        step: 0.01,
        type: 'knob',
      },
    ],
  },
  stereowidener: {
    type: 'stereowidener',
    name: 'Stereo Widener',
    icon: '📐',
    parameters: [
      {
        name: 'Width',
        value: 0.5,
        min: 0,
        max: 1,
        step: 0.01,
        type: 'knob',
      },
      {
        name: 'Dry/Wet',
        value: 0.5,
        min: 0,
        max: 1,
        step: 0.01,
        type: 'knob',
      },
    ],
  },
  tremolo: {
    type: 'tremolo',
    name: 'Tremolo',
    icon: '〰️',
    parameters: [
      {
        name: 'Frequency',
        value: 10,
        min: 0.1,
        max: 20,
        step: 0.1,
        type: 'knob',
        unit: 'Hz',
      },
      {
        name: 'Depth',
        value: 0.5,
        min: 0,
        max: 1,
        step: 0.01,
        type: 'knob',
      },
      {
        name: 'Spread',
        value: 40,
        min: 0,
        max: 180,
        step: 1,
        type: 'knob',
        unit: '°',
      },
      {
        name: 'Dry/Wet',
        value: 0.5,
        min: 0,
        max: 1,
        step: 0.01,
        type: 'knob',
      },
    ],
  },
  vibrato: {
    type: 'vibrato',
    name: 'Vibrato',
    icon: '🎵',
    parameters: [
      {
        name: 'Frequency',
        value: 5,
        min: 0.1,
        max: 20,
        step: 0.1,
        type: 'knob',
        unit: 'Hz',
      },
      {
        name: 'Depth',
        value: 0.1,
        min: 0,
        max: 1,
        step: 0.01,
        type: 'knob',
      },
      {
        name: 'Dry/Wet',
        value: 0.5,
        min: 0,
        max: 1,
        step: 0.01,
        type: 'knob',
      },
    ],
  },
};

export const EFFECT_ORDER: EffectType[] = [
  'compressor',
  'distortion',
  'bitcrusher',
  'autofilter',
  'autowah',
  'filter',
  'phaser',
  'chorus',
  'tremolo',
  'vibrato',
  'autopanner',
  'stereowidener',
  'delay',
  'pingpongdelay',
  'reverb',
];
